#%RAML 1.0 ResourceType
post:
      body:
        application/json:
          example: |
            <<examplereference1>>
      responses:
        200:
          body:
            application/json:
              example: |
                <<examplereference2>>
        400:
          body:
            application/json:
              example: |
                <<examplereference3>>
      