#%RAML 1.0
title: insuranceTrail1
uses:
  library: library.raml 
  # Library.raml file contails Failure(error) Responses as Traits, Datatypes for GetPolicies, AddCustomer & claim details, ResourdeTypes named a Collection
  
resourceTypes:
  postresource: !include resourceType.raml 


/company:

  /policies:
    get:
      description: Get a list of all policies offered by the company
      is: library.failure
      responses:
        200:
          body:
            application/json:
              type: library.policy[]
              example: !include examples/company-policies/GET.json
    post:
      # adding a new policy
      
      is:
        - library.failure
      description: Create a new policy
      
      body:
        application/json:
          type: library.policy[]
          example: !include examples/company-policies/POST body.json
            
      responses:
        201:
          body:
            application/json:
              example: {"message":"added a new policy"}
              
    /{policyNumber}: # get details of policy & adding a new customer to it and deleting the policy
      get:
        is:
          - library.failure
        description: Get details of a specific policy by policy number
    
        responses:
          200:
            body:
              application/json:
                example: !include examples/company-policies-{policynumber}/GET.json
      put:
        is:
          - library.failure
        description: Add a customer to a specific policy
        
        body:
          application/json:
            type: library.addcustomer
            example: !include examples/company-policies-{policynumber}/PUT body.json
        responses:
          200:
            body:
              application/json:
                example: "Added to mahesh to the Health insurance policy and got the policyID = Mahesh001 as an Acknowledgement"


  /{PolicyHolderName}:
    uriParameters:
      PolicyHolderName:
        required: true
        type: string
        pattern: ^[a-zA-Z\s]+$
        
    get:
      is:
        - library.failure
      description: Get details of all policies by policy holder name
      
      responses:
        200:
          body:
            application/json:
              example: !include examples/company-{policyholderName}/GET.json

  /{policyID}: # getting the paticular policy by the policyID
    get:
      is:
        - library.failure
      responses:
        200:
          body:
            application/json:
              type: library.addcustomer
              example: !include examples/company-policyID/GET.json
    post: #payment required for the policy
      description: payments
      body:
        application/json:
          example: {
            "transactionID": "TRID76234567987",
            "Ammount": "5000",
            "status": "Paid through UPI payments"
          }
      responses:
        200:
          body:
            application/json:
              example: {"message": "Payment successfull"}

    /claim:
      # by using the resourceTypes 
      type: 
        postresource: # from resource Type.raml file
          examplereference1: {
                "claimNumber": "C002",
                "dateSubmitted": "2023-03-15",
                "status": "approved",
                "policyNumber": "P001",
                "claimant": "John Smith",
                "amount": 1000,
                "description": "Theft",
                "adjusterNotes": "Police report received and approved"
              }
          examplereference2: "claimed"
          examplereference3: "need more deatils"
          # referencing the examples that are mentioned in the resourceTypes(Post method)
         
  /{claimspolicyNumber}:
    is:
      - library.failure
    
    type: # resourceType from the library file
      library.collectionname:
        refence1: [
                  {
                    "claimNumber": "C001",
                    "dateSubmitted": "2023-04-01",
                    "status": "pending",
                    "policyNumber": "P001",
                    "claimant": "Jane Doe",
                    "amount": 5000,
                    "description": "Car accident",
                    "adjusterNotes": "Waiting for police report"
                  },
                  {
                    "claimNumber": "C002",
                    "dateSubmitted": "2023-03-15",
                    "status": "approved",
                    "policyNumber": "P001",
                    "claimant": "John Smith",
                    "amount": 1000,
                    "description": "Theft",
                    "adjusterNotes": "Police report received and approved"
                  }
              ]


  /{claimNumber}:
    get:
      description: get the claim status
      responses:
        200:
          body:
            application/json:
              type: library.claimpost
              example: {
                    "claimNumber": "C001",
                    "dateSubmitted": "2023-04-01",
                    "status": "pending",
                    "policyNumber": "P001",
                    "policyHolderName": "Jane Doe",
                    "amount": 5000,
                    "description": "Car accident",
                    "adjusterNotes": "report approved"
                  }
    


