#%RAML 1.0 Library
traits:
  failure:
    responses:
      400:
        body:
          application/json:
            example: "sdfgn"
      
      404:
        body:
          application/json:
            example: "sdf"
      500:
        body:
          application/json:
            example: "adscfg"